name: 'KubeLinter reporter'
description: 'Make a report for KubeLinter results'

branding:
  icon: settings
  color: blue

inputs:
  file:
    required: true
    description: 'Path to KubeLinter JSON results file'
  show-filename:
    required: false
    description: |-
      Show references to filenames that have errors in the report
    default: 'true'
  mode:
    required: false
    description: |-
      A multi-line input with the following values:
      - pr-comment - report will be added as a comment on PR.
      - check - report will be added in a GitHub check.
      - summary - report will be added as a summary.
  token:
    required: true
    description: 'Your GitHub token'
    default: ${{ github.token }}
  fail-on-error:
    required: false
    description: 'Fail the action if errors are found on the report'
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
